Repository sliit-foss/bashaway-official, pull requests merged in 2023-07, with the labels that each got.

#4 Feat: completed prizes section on landing page
  apps/2023/src/components/landing/index.jsx
  apps/2023/src/components/landing/prizes.jsx
  apps/2023/src/pages/landing.jsx
Labels: enhancement

#5 Feat: completed past events section on landing page
  apps/2023/src/components/landing/index.jsx
  apps/2023/src/components/landing/past-events.jsx
  apps/2023/src/icons/index.jsx
  apps/2023/src/icons/link.jsx
  apps/2023/src/pages/landing.jsx
Labels: changed requested :eyes:, enhancement

#8 Feature/rules
  .github/actions/build/action.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-clean.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/prod-deploy.yml
  apps/2023/public/assets/images/gallery/1.jpg
  apps/2023/public/assets/images/gallery/2.jpg
  apps/2023/public/assets/images/gallery/3.jpg
  apps/2023/src/components/common/badges/section.jsx
  apps/2023/src/components/common/component-stack.jsx
  apps/2023/src/components/common/index.jsx
  apps/2023/src/components/common/typography/body.jsx
  apps/2023/src/components/common/typography/highlight.jsx
  apps/2023/src/components/common/typography/index.jsx
  apps/2023/src/components/landing/competition.jsx
  apps/2023/src/components/landing/gallery.jsx
  apps/2023/src/components/landing/hero.jsx
  apps/2023/src/components/landing/index.jsx
  apps/2023/src/components/landing/marquee.jsx
  apps/2023/src/components/landing/mission.jsx
  apps/2023/src/components/landing/partners.jsx
  apps/2023/src/components/landing/prizes/data.json
  apps/2023/src/components/landing/prizes/index.jsx
  apps/2023/src/components/landing/rules/data.json
  apps/2023/src/components/landing/rules/index.jsx
  apps/2023/src/components/landing/sponsors/data.json
  apps/2023/src/components/landing/sponsors/index.jsx
  apps/2023/src/hooks/effect-once.jsx
  apps/2023/src/hooks/index.js
  apps/2023/src/hooks/index.jsx
  apps/2023/src/pages/landing.jsx
  lefthook.yml
  package.json
Labels: changed requested :eyes:

#11 Fix: added grayscale animation to gallery
  apps/2023/src/components/common/component-stack.jsx
  apps/2023/src/components/landing/gallery.jsx
Labels: enhancement

#10 Refactor: change the favicon
  apps/2023/public/assets/icons/favicon.svg
Labels: enhancement

#12 Feat: added timeline
  apps/2023/src/components/common/component-stack.jsx
  apps/2023/src/components/landing/index.jsx
  apps/2023/src/components/landing/partners.jsx
  apps/2023/src/components/landing/past-events.jsx
  apps/2023/src/components/landing/rules/index.jsx
  apps/2023/src/components/landing/timeline/data.json
  apps/2023/src/components/landing/timeline/index.jsx
  apps/2023/src/hooks/index.jsx
  apps/2023/src/hooks/window-dimension.jsx
  apps/2023/src/pages/landing.jsx
Labels: enhancement

#14 Reduced rule font size
  .github/workflows/quality-checks.yml
  apps/2023/src/components/landing/rules/index.jsx
Labels: enhancement, review needed :guard:

#15 Feat: added scroll on nav item click
  apps/2023/src/components/common/layout/header.jsx
  apps/2023/src/components/landing/competition.jsx
  apps/2023/src/components/landing/prizes/index.jsx
  apps/2023/src/components/landing/rules/index.jsx
  apps/2023/src/components/landing/sponsors/index.jsx
  apps/2023/src/components/landing/timeline/index.jsx
Labels: enhancement, review needed :guard:

#16 Feat: added scroll to section based on router hash
  apps/2023/src/app.jsx
  apps/2023/src/components/common/layout/header.jsx
  apps/2023/src/components/landing/rules/index.jsx
  apps/2023/src/hooks/index.jsx
  apps/2023/src/hooks/scroll.jsx
Labels: enhancement
